### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Omgise** [Aira-Sakuranomiya/CleanFlashInstaller#2]
System.UnauthorizedAccessException: 对路径“Flash8.ocx”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileInfo.Delete()
   在 CleanFlashCommon.FileUtil.DeleteFile(FileInfo file)
   在 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   在 CleanFlashCommon.FileUtil.RecursiveDelete(DirectoryInfo rootDir, DirectoryInfo baseDir, String filename)
   在 CleanFlashCommon.Uninstaller.DeleteFlashPlayer()
   在 CleanFlashInstaller.InstallForm.<>c__DisplayClass15_0.<BeginInstall>b__0()

**Comment by Aira-Sakuranomiya** [comment]
I'm sorry but this repo is only a mirror of https://gitlab.com/cleanflash/installer/

Please report issues at https://gitlab.com/cleanflash/installer/-/issues
